INSERT INTO `team` VALUES ('1','Infinity'),
('2','Clowns'),
('3','Cyberpunk'),
('4','Game Changers'),
('5','Lynch'),
('6','Hill'),
('7','McCullough'),
('8','Rain'),
('9','Graham'),
('10','Headshot'),
('11','Plazma'),
('12','Rath and Sons'),
('13','Haag-Hammes'),
('14','Wolves'),
('15','Boring Team'),
('16','Killers'),
('17','Megaplayers'),
('18','Vampires'),
('19','Jakubowich'),
('20','Popcorn'); 

