CREATE TABLE `device` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `platform_id` INT UNSIGNED NOT NULL,
  `rating` INT UNSIGNED NOT NULL,
  `condition` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`));