CREATE TABLE `pc` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `device_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `cpu` VARCHAR(50) NOT NULL DEFAULT 1,
  `gpu` VARCHAR(50) NOT NULL,
  `price` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`id`));