CREATE TABLE `tariff` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `hours` INT UNSIGNED NOT NULL,
  `room_id` INT UNSIGNED NOT NULL,
  `cost` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);